services:
  app:
    build: .
    container_name: library-app
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/library-project
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 8986Kh-4
      SPRING_LIQUIBASE_ENABLED: "true"
      SPRING_LIQUIBASE_CHANGE_LOG: classpath:db/changelog/db.changelog-master.xml
    networks:
      - backend

  db:
    image: postgres:15
    container_name: library-db
    environment:
      POSTGRES_DB: library-project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8986Kh-4
    ports:
      - "5435:5432"
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  backend:
